trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'pocbluegreendeployment'
  acrName: 'bluegreendeployment'  # Without .azurecr.io
  azureSubscriptionEndpoint: 'Ankit_Service_Connection'
  containerAppName: 'poc-bluegreen-app'
  resourceGroup: 'RG_Ankit_Pathak'
  environmentName: 'aca-env'

stages:
# ------------- BUILD AND PUSH STAGE ----------------
- stage: Build
  displayName: Build and Push
  jobs:
  - job: BuildAndPush
    displayName: Docker Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Cloning repository..."
        git clone https://github.com/ankitp-optimus/poc_blue-_green.git src
        ls -la src/
        find src/ -name "dockerfile" -o -name "Dockerfile"
      displayName: Clone and Verify Structure

    - task: AzureCLI@2
      displayName: Login to Azure and ACR
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - script: |
        cd src
        docker build -t $(acrName).azurecr.io/$(imageName):$(tag) \
                     -t $(acrName).azurecr.io/$(imageName):latest \
                     -f DockerFile .
      displayName: Docker Build

    - script: |
        docker push $(acrName).azurecr.io/$(imageName):$(tag)
        docker push $(acrName).azurecr.io/$(imageName):latest
      displayName: Docker Push
