trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'pocbluegreendeployment'
  acrName: 'bluegreendeployment'  # Without .azurecr.io
  azureSubscriptionEndpoint: 'Ankit_Service_Connection'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: BuildAndPush
    displayName: Docker Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    # 1. First clone and verify the repository structure
    - script: |
        echo "Cloning repository..."
        git clone https://github.com/ankitp-optimus/poc_blue-_green.git src
        echo "Contents of src directory:"
        ls -la src/
        echo "Looking for dockerfile:"
        find src/ -name "dockerfile" -o -name "Dockerfile"
      displayName: Clone and Verify Structure

    # 2. Login to Azure and ACR
    - task: AzureCLI@2
      displayName: Login to Azure and ACR
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    # 3. Build using explicit path to dockerfile
    - script: |
        cd src
        docker build -t $(acrName).azurecr.io/$(imageName):$(tag) -f DockerFile .
      displayName: Docker Build

    # 4. Push the image
    - script: |
        docker push $(acrName).azurecr.io/$(imageName):$(tag)
      displayName: Docker Push